# Generated by Django 3.2.15 on 2022-10-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
